### ISSUE TITLE
Tabs 组件点击切换错误

### ISSUE THREAD

**Issue by huzhengen** [FrankFang/bczNwAFhBrmV#3]
把项目 clone 下来，删除 yarn.lock，再 yarn，yarn dev，打开网页，点到 Tabs 组件，点击切换导航出错。

```
git clone https://github.com/FrankFang/bczNwAFhBrmV.git
cd bczNwAFhBrmV/
rm -rf yarn.lock // 不删除 yarn.lock 不会出错
yarn
yarn dev
```
打开：http://localhost:3000/#/doc/tabs

点击“导航1”“导航2”，切换出错

（不删除 yarn.lock 的话，没有问题）

**Comment by FrankFang** [comment]
最新的视频已经解决了这个问题，是因为 Vue 3 rc13 改了 watchEffect 的默认行为：https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#breaking-changes

**Comment by huzhengen** [comment]
好的
